version: "3.2"

services:
  face-restoration-worker:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
        - .env
    environment:
        MODELS_PATH: /models/
        DEVICE: ${DEVICE}
    image: rmrfred/face-restoration-worker:latest
    restart: always
    volumes:
      - /srv/docker/face-restoration-worker/logs:/logs

  face-restoration-worker-client:
    build: 
      context: .
      dockerfile: Dockerfile
    image: rmrfred/face-restoration-worker-client:latest
    volumes:
      - ./face_restoration_worker_client:/face_restoration_worker_client
      - ./dist:/dist
    command: bash -c "python3.10 -m pip wheel --no-deps -w /dist /"